# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# See also: https://github.com/marketplace/actions/bazel-action

name: Continuous Integration
on:
  # Avoid triggering on pushes to /all/ open PR branches.
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  # This lets us trigger manually from the UI.
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-22.04
          - ubicloud-standard-2
          - ubicloud-standard-4
          - ubicloud-standard-8
          - ubicloud-standard-16
          - ubicloud-standard-30
          - ubicloud-standard-60
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 600
    steps:
      - uses: actions/checkout@v2

      - name: Show cpu info
        run: lscpu

      - if: matrix.runner == 'ubuntu-22.04' || matrix.runner == 'ubicloud-standard-2' || matrix.runner == 'ubicloud-standard-2-arm'
        name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false

      - name: Restore Nightly Bazel Cache
        if: false
        uses: actions/cache/restore@v4
        with:
          path: "~/.cache/bazel"
          key: bazel-cache-nightly-${{ runner.os }}-${{ github.sha }}
          restore-keys: bazel-cache-nightly-${{ runner.os }}-

      - name: Install dependencies via apt
        run: sudo apt-get install python3-distutils python3-dev python-is-python3 libtinfo5  build-essential liblapack-dev libblas-dev gfortran

      - name: Bazel Build Tools (opt)
        run: |
          bazel build -c opt --noshow_progress --test_output=errors -- //xls/dslx:interpreter_main //xls/dslx/ir_convert:ir_converter_main //xls/tools:opt_main //xls/tools:codegen_main

      - name: Bazel Test xls/... (opt)
        run: |
          bazel test -c opt --noshow_progress --test_output=errors -- //xls/... -//xls/contrib/... -//xls/dev_tools/...

      - name: Bazel Test Including Contrib & DevTools (opt)
        run: |
          bazel test -c opt --noshow_progress --test_output=errors -- //...
