# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# See also: https://github.com/marketplace/actions/bazel-action

name: Solo Bazel Test (Ubuntu 22.04)

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Bazel Target Pattern'
        default: '//xls/dslx:interpreter_test'
        required: true
      runs_per_test:
        description: 'Number of Runs'
        default: '1'
        required: true

env:
  BAZEL_TARGET: '//xls/dslx:interpreter_test'
  BAZEL_RUNS_PER_TEST: '1'

jobs:
  build:
    name: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-22.04
          - ubicloud-standard-2
          - ubicloud-standard-4
          - ubicloud-standard-8
          - ubicloud-standard-16
          - ubicloud-standard-30
          - ubicloud-standard-2-arm
          - ubicloud-standard-4-arm
          - ubicloud-standard-8-arm
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 600
    steps:
      - uses: actions/checkout@v2

      - name: Show cpu info
        run: lscpu

      - name: Restore Nightly Bazel Cache
        if: false
        uses: actions/cache/restore@v4
        with:
          path: "~/.cache/bazel"
          key: bazel-cache-nightly-${{ runner.os }}-${{ github.sha }}
          restore-keys: bazel-cache-nightly-${{ runner.os }}-

      - name: Install dependencies via apt
        run: sudo apt-get install python3-distutils python3-dev python-is-python3 libtinfo5  build-essential liblapack-dev libblas-dev gfortran

      - name: Bazel Test Target (opt)
        run: |
          bazel test -c opt --test_output=all --runs_per_test=$BAZEL_RUNS_PER_TEST -- $BAZEL_TARGET
